"""Config loading and validation — the invariants that protect the experiment."""

from __future__ import annotations

import copy

import pytest
import yaml
from evolution.config import DEFAULT_CONFIG_PATH, ExperimentConfig, load_config


@pytest.fixture
def raw() -> dict:
    data = yaml.safe_load(DEFAULT_CONFIG_PATH.read_text(encoding="utf-8"))
    data["run_id"] = "test-run"
    return data


def test_shipped_config_is_valid(raw: dict) -> None:
    config = ExperimentConfig.model_validate(raw)
    assert config.evolution.agents_per_generation == 10


def test_run_id_autogenerated_when_null(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GEMINI_API_KEY", "dummy")
    config = load_config()
    assert config.run_id  # timestamp-derived
    assert config.results_dir.name == config.run_id


def test_missing_api_key_is_fatal(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GEMINI_API_KEY", "")
    with pytest.raises(RuntimeError, match="GEMINI_API_KEY"):
        load_config()


def test_api_key_excluded_from_repr(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("GEMINI_API_KEY", "super-secret-value")
    config = load_config()
    assert "super-secret-value" not in repr(config)


def test_placeholder_model_ids_are_detected(raw: dict) -> None:
    unset = copy.deepcopy(raw)
    unset["models"] |= {
        "worker": "PLACEHOLDER-flash",
        "curator": "PLACEHOLDER-pro",
        "judge": "gemini-2.5-pro",
    }
    placeholders = ExperimentConfig.model_validate(unset).models.placeholders()
    assert set(placeholders) == {"worker", "curator"}


def test_shipped_config_has_no_placeholder_models(raw: dict) -> None:
    """Launching with an unset model ID should be impossible by inspection."""
    assert ExperimentConfig.model_validate(raw).models.placeholders() == []


def test_shipped_models_are_pinned_not_aliases(raw: dict) -> None:
    """Aliases move and previews get withdrawn; either breaks comparability
    between the first and last generation of a run (config comment, AGENTS.md §3)."""
    models = ExperimentConfig.model_validate(raw).models
    for role, model_id in (
        ("worker", models.worker),
        ("curator", models.curator),
        ("judge", models.judge),
    ):
        assert not model_id.endswith("-latest"), f"{role} pins a moving alias"


class TestGroupSplit:
    """The control group is the experiment's only baseline (AGENTS.md §9)."""

    def test_scheduled_split_shifts_toward_memory(self, raw: dict) -> None:
        evo = ExperimentConfig.model_validate(raw).evolution
        assert evo.split_for(1) == (3, 7)
        assert evo.split_for(5) == (6, 4)
        assert evo.split_for(12) == (8, 2)

    def test_generations_past_schedule_use_last_rule(self, raw: dict) -> None:
        evo = ExperimentConfig.model_validate(raw).evolution
        assert evo.split_for(10_000) == (8, 2)

    def test_split_starving_control_group_is_rejected(self, raw: dict) -> None:
        raw["evolution"]["group_split_schedule"] = [
            {"until_generation": 999, "group_a": 9}
        ]
        with pytest.raises(ValueError, match="min_group_b"):
            ExperimentConfig.model_validate(raw)

    def test_split_larger_than_population_is_rejected(self, raw: dict) -> None:
        raw["evolution"]["group_split_schedule"] = [
            {"until_generation": 999, "group_a": 11}
        ]
        with pytest.raises(ValueError, match="out of range"):
            ExperimentConfig.model_validate(raw)


def test_held_out_tasks_cannot_overlap_selection(raw: dict) -> None:
    raw["tasks"]["selection"] = ["cat_bounce", "todo_api"]
    raw["tasks"]["held_out"] = ["todo_api"]
    with pytest.raises(ValueError, match="both selection and held_out"):
        ExperimentConfig.model_validate(raw)
